### ISSUE TITLE
pip install error: egg_info failed with error code 1

### ISSUE THREAD

**Issue by todrobbins** [mod2/momentum#1]
```
todrobbins:momentum todrobbins$ pip install -r requirements.txt
Collecting Django==1.7 (from -r requirements.txt (line 1))
  Downloading Django-1.7-py2.py3-none-any.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 74kB/s
Collecting pytz==2014.10 (from -r requirements.txt (line 2))
  Downloading pytz-2014.10-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 479kB 1.2MB/s
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 3))
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/8h/kkv31w1x2sj2fhzr2bhtrz0h0000gn/T/pip-build-vtquwveu/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/8h/kkv31w1x2sj2fhzr2bhtrz0h0000gn/T/pip-build-vtquwveu/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8h/kkv31w1x2sj2fhzr2bhtrz0h0000gn/T/pip-build-vtquwveu/wsgiref
```

**Comment by todrobbins** [comment]
`pip install` worked with Python 2.7. My bad!
